load_from:
  # Each entry here corresponds to a service in the docker-compose file that exposes pipelines.
  - grpc_server:
      host: docker_exchangerates_pipelines
      port: 4000
      location_name: "exchangerate_pipelines"